name: potato_notes
description: Official POSP notes app
publish_to: "none"
version: 2.0.1+21

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animated_vector:
    git: https://github.com/PotatoProject/animated_vector
  animations: ^2.0.2
  archive: ^3.1.11

  back_button_interceptor: ^5.0.2
  biometric_storage: ^4.0.1
  bitsdojo_window: ^0.1.1+1
  blurhash_dart: ^1.1.0

  collection: ^1.15.0
  cross_file: ^0.3.2
  cryptography: ^2.0.5
  cupertino_icons: ^1.0.4

  diffutil_dart: ^3.0.0
  dio: ^4.0.4
  drift: ^1.4.0

  easy_localization:
    git: https://github.com/HrX03/easy_localization

  file_picker: ^4.3.3
  file_selector: ^0.8.3
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.8.2
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.6.0
  flutter_keyboard_visibility: ^5.1.1
  flutter_local_notifications: ^9.2.0
  flutter_mobx: ^2.0.4
  flutter_staggered_grid_view: ^0.6.1

  http: ^0.13.3

  image: ^3.1.1
  image_picker: ^0.8.4+7
  image_picker_for_web: ^2.1.5
  image_size_getter: ^1.0.0
  in_app_update: ^2.0.0
  intl: ^0.17.0

  json_annotation: ^4.4.0

  local_auth: ^1.1.10
  loggy:
    git: https://github.com/HrX03/loggy

  material_design_icons_flutter: ^5.0.6595
  mobx: ^2.0.6+1
  monet: ^0.1.0

  package_info_plus: ^1.0.3
  path: ^1.8.1
  path_drawing: ^1.0.0
  path_provider: ^2.0.8

  quick_actions: ^0.6.0+9

  recase: ^4.0.0

  share_plus: ^3.0.4
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  sqflite_common_ffi: ^2.1.0+2
  sqlcipher_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      path: sqlcipher_flutter_libs
  sqlite3: ^1.5.1
  
  toml: ^0.12.0

  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.18
  uuid: ^3.0.4

  waterfall_flow: ^3.0.2
  webcrypto:
    git: https://github.com/gargakshit/webcrypto.dart

  xml: ^5.3.1

dev_dependencies:
  build_runner: ^2.1.7
  drift_dev: ^1.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  lint: ^1.8.2
  mobx_codegen: ^2.0.5+2
  mockito: ^5.0.17

flutter:
  uses-material-design: true
  assets:
    - config.json
    - themes/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: ValeraRound
      fonts:
        - asset: fonts/ValeraRound.ttf

dependency_overrides:
  path: ^1.8.1
  path_parsing: ^1.0.0