name: potato_notes
description: Official POSP note app
version: 1.5.2+14

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.5.9-pre.270'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite:
  path:
  shared_preferences:
  url_launcher:
  provider:
  flutter_material_color_picker:
  intl:
  image_picker:
  back_button_interceptor:
  flutter_local_notifications:
  share:
  permission_handler:
  file_picker:
  intl_translation:
  package_info:
  http:
  crypto:
  simple_animations:
  cached_network_image: ^2.0.0-rc
  outline_material_icons:
  community_material_icon:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: CustomIcons
      fonts:
      - asset: fonts/CustomIcons.ttf
    - family: GoogleSans
      fonts:
      - asset: fonts/GoogleSans-Regular.ttf
      - asset: fonts/GoogleSans-Medium.ttf
        weight: 500
      - asset: fonts/GoogleSans-Bold.ttf
        weight: 600
