name: potato_notes
description: Official POSP note app
version: 1.4.0+8

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.5.9-pre.270'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.0

  sqflite:
  path:
  shared_preferences:
  url_launcher:
  provider:
  flutter_material_color_picker:
  intl:
  image_picker:
  back_button_interceptor:
  flutter_local_notifications:
  share:
  permission_handler:
  file_picker:
  flutter_colorpicker:
  intl_translation:
  package_info:
  http:
  crypto:
  simple_animations:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  CustomIcons
      fonts:
      - asset: fonts/CustomIcons.ttf
