name: potato_notes
description: Official POSP note app
version: 1.5.2+15

environment:
  sdk: '>=2.2.2 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.5.9-pre.270'

dependencies:
  flutter:
    sdk: flutter

  moor_flutter: ^1.4.0
  json_serializable:
  sqflite:
  path_provider:
  provider:
  streams_channel:
  flutter_markdown:
  outline_material_icons:
  community_material_icon:
  flutter_staggered_grid_view:
  photo_view:
  image_picker:
  
  rich_text_editor:
    git:
      url: https://github.com/namhyun-gu/flutter_rich_text_editor
  spicy_components:
    git: https://github.com/HrX03/SpicyUIComponents

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^1.4.0
  build_runner:

flutter:
  uses-material-design: true